name: CI-Pipeline
on:
  push:
    branches: [ master, feature/* ]
  pull_request:

jobs:
  Build:
    runs-on: self-hosted
    container:
      image: node:22-bullseye
    steps:
        - uses: actions/checkout@v5
        - name: Install dependencies
          run: npm install
        - name: Run Tests
          run: npm test
    
     

